name: ipyleaflet-gl-vector-layer-plugin
channels:
  - conda-forge
dependencies:
  - ipyleaflet>=0.13.5
  - jupyterlab
  - jupyter-packaging
  - nodejs
  - yarn
  - python
  - pip
  - ipywidgets
  - numpy
  - traitlets
  - traittypes
